package com.chronos.agent

import android.content.Context
import java.util.concurrent.atomic.AtomicBoolean

object Chronos {
    private val initialized = AtomicBoolean(false)
    
    // Store application context to prevent Activity leaks
    private var appContext: Context? = null

    /**
     * Initializes Chronos.
     * 
     * @param context Application or Activity context. Uses applicationContext to prevent leaks.
     * @throws SecurityException if called in a non-debug build.
     */
    fun initialize(context: Context) {
        // HARD SAFETY CHECK: Determine if we are running in a debuggable build
        // We rely on the BuildConfig field generated by AGP for this library.
        if (!BuildConfig.DEBUG) {
            throw SecurityException(
                "Chronos Safety Violation: Chronos must NEVER be included in a release build. " +
                "Please check your dependencies and ensure you are using 'debugImplementation'."
            )
        }

        if (initialized.getAndSet(true)) {
            return
        }
        
        // Use application context to prevent Activity/Fragment leaks
        appContext = context.applicationContext

        // TODO: Initialize internal components
    }
    
    /**
     * Returns true if Chronos has been initialized.
     */
    fun isInitialized(): Boolean = initialized.get()
}
